### ISSUE TITLE
Color code progress bar and torrent list

### ISSUE THREAD

**Issue by Blizzardfall** [witalihirsch/qBitTorrent-fluent-theme#10]
It looks great at the current state, but it's hard to distinguish downloading torrents from completed/paused ones.
It can be much more intuitive if the list is color coded like orange for paused, blue for completed, red for errored and such.

I think Dracula theme is a great example of this:
![화면 캡처 2022-06-19 201145](https://user-images.githubusercontent.com/19769002/174478139-179d485b-f6eb-42fd-9429-6aea8e4871d9.png)

Thanks for the great theme btw

**Comment by witalihirsch** [comment]
firstly, there are two indicators showing the loading status
![image](https://user-images.githubusercontent.com/73841541/174491186-478433d4-a69a-4d67-b649-1aedca32e300.png)
secondly, it looks rather bad in my opinion and doesn't fit into the fluent design
but, I made everything as simple as possible and you can edit the .qss file as you like and then run the .bat file in the builds folder, after which the theme file will be created.

**Comment by Blizzardfall** [comment]
I can understand that it can look bad on this as Dracula is more focused on functionality side, but yeah even the colored icons can be a huge help. I just found it hard to know the status at a glance when staring using this one.
Well, I might be the bigger problem having dozens of torrent just waiting to be downloaded.

**Comment by witalihirsch** [comment]
okay, colored icons for loading status sounds logical, i'll do that in the next release
