### ISSUE TITLE
Download priority selection box label misassigned

### ISSUE THREAD

**Issue by megablue** [witalihirsch/qBitTorrent-fluent-theme#11]
![image](https://user-images.githubusercontent.com/164641/175560978-7a445d78-7213-4682-a9af-be86ffd6c66a.png)

**Comment by XKillSwitchXxx** [comment]
This issue is on qBitTorrent, I had the same even when running on stock skin

**Comment by witalihirsch** [comment]
what version of the program are you using? I don't have download priority

**Comment by VladWinner** [comment]
> I don't have download priority

v4.4.3.1
![image](https://user-images.githubusercontent.com/13555921/185520750-ba275e6a-d0a1-41e5-81b8-3a313aa0c9f3.png)

Use Right Mouse Button to re-enable it.
![image](https://user-images.githubusercontent.com/13555921/185520877-5be54b7b-9a24-49e5-88fa-525212918188.png)

**Comment by witalihirsch** [comment]
fixed
