### ISSUE TITLE
Unable to resize the torrent addition window

### ISSUE THREAD

**Issue by sg-007** [witalihirsch/qBitTorrent-fluent-theme#12]
The window snaps every time I try to resize it. By default, the scale of my 14-inch laptop monitor is 150%. Resizing works for scale below 150%.

https://user-images.githubusercontent.com/55142587/175610273-d03620e7-0379-456b-b4c1-0156959fb232.mp4

**Comment by sagars007** [comment]
Yeah same problem here even with 125% or 100% display scaling

**Comment by witalihirsch** [comment]
I tried to make this window smaller, but not to the detriment of the design

**Comment by sg-007** [comment]
The problem still exists....

**Comment by witalihirsch** [comment]
in the new release i made the window as small as possible without ruining the theme
