### ISSUE TITLE
Light theme is broken

### ISSUE THREAD

**Issue by maicol07** [witalihirsch/qBitTorrent-fluent-theme#13]
Hi,
the light theme is completely black:
![image](https://user-images.githubusercontent.com/9463142/184528964-507e1b7e-3710-41a3-9161-c1f79c510152.png)

Can you fix it?
Thanks

**Comment by witalihirsch** [comment]
What's the version of qBitTorrent u use? Qt5 or Qt6?

**Comment by maicol07** [comment]
Qt6

**Comment by witalihirsch** [comment]
Use Qt5 version and for mica version of theme use Mica for everyone with my settings or no-mica theme (for Qt6 theme will later)
