### ISSUE TITLE
Qt6

### ISSUE THREAD

**Issue by sn-o-w** [witalihirsch/qBitTorrent-fluent-theme#14]
Hi,

Do you plan to adapt your theme for the Qt6 version as well?

2 months ago I tried your theme, but it looked ugly, at least some elements never looked like the posted screenshots.

And now I realize I need qBitTorrent on Qt5, but I always used the Qt6 version. 😥

> The v4.4.x series will probably be the last one that supports Qt5 and therefore Windows 7 and 8. It will see releases at least until the summer of 2022.

Btw soon they seem to switch to Qt6 anyways.

**Comment by witalihirsch** [comment]
Added support for Qt6 version
