### ISSUE TITLE
Mica Background Effect isnt working (even though i enabled the Extend Background into Client Toggle) tested on two different computers

### ISSUE THREAD

**Issue by GitExploraa** [witalihirsch/qBitTorrent-fluent-theme#17]
as the title says, i followed all the mentionned steps, but couldnt get this to work, so its probably a bug

**Comment by witalihirsch** [comment]
what version of windows do you have?

**Comment by GitExploraa** [comment]
latest Windows 11 Beta Release (21H2)

**Comment by witalihirsch** [comment]
okay, send me screenshot of mica for everyone

**Comment by GitExploraa** [comment]
> okay, send me screenshot of mica for everyone

here
![image](https://user-images.githubusercontent.com/44654056/190926882-e2d3e020-f0b7-4ec3-9d4c-fd1726ac5b60.png)
![image](https://user-images.githubusercontent.com/44654056/190926892-123bee00-1786-49a4-b5f8-d0249ae67b12.png)

**Comment by witalihirsch** [comment]
it's hard to say exactly what the problem is. perhaps these are problems of the new build of windows 11 or its incompatibility with mica for everyone. i can say that everything worked on the stable version of windows 11

**Comment by GitExploraa** [comment]
> f the new build of

emmh okay, i see, i'll wait for the stable release of the new Windows 11 Update (or an update for Mica for everyone) and let you know if anything changes, Thanks

**Comment by GitExploraa** [comment]
good news, installing the latest version 2.6 did make this work, maybe i choosed the wrong or something before

**Comment by witalihirsch** [comment]
great :)
