### ISSUE TITLE
Spacing issue in menus and windows.

### ISSUE THREAD

**Issue by rangan2510** [witalihirsch/qBitTorrent-fluent-theme#18]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/32454244/190886141-7fcddda6-22f7-4e03-b78c-e46d463737ad.png">
Force recheck window

<img width="198" alt="image" src="https://user-images.githubusercontent.com/32454244/190886161-02b2ab18-0909-49ce-bc01-cbe114e658e3.png">
On right clicking an errored torrent.

**Comment by rangan2510** [comment]
This is present in both mica and no-mica themes. Also, this is the state of mice for everyone. 
![image](https://user-images.githubusercontent.com/32454244/190902043-3027dfd7-1727-490e-9cc8-8ac68c839784.png)

**Comment by witalihirsch** [comment]
fixed

**Comment by rangan2510** [comment]
The popup window sizing is fixed, but the menu sizing issue still remains. It happens when I click on an errored torrent.

**Comment by witalihirsch** [comment]
i tried to find a way to fix it, but the only thing that worked was to change the color of the selection so that it wasn't very conspicuous
