### ISSUE TITLE
Request to update the System tray icon

### ISSUE THREAD

**Issue by GitExploraa** [witalihirsch/qBitTorrent-fluent-theme#19]
the icon looks very confusing imo as i often confuse it with other downloading apps... it'd be better to just have the stock Qbittorrent icon or one that looks like it but follows fluent design
![image](https://user-images.githubusercontent.com/44654056/190926966-8afd36a7-0471-4f76-a854-e3cb303f2dfb.png)

**Comment by witalihirsch** [comment]
select "Normal" icon style in settings

![image](https://user-images.githubusercontent.com/73841541/190954364-c132aa55-3aa3-4f3e-a675-9e54c2665254.png)

![image](https://user-images.githubusercontent.com/73841541/190954282-bed6d7d4-041c-4090-bb12-f45e33fcaccc.png)

**Comment by GitExploraa** [comment]
Great, Thanks a lot!
