### ISSUE TITLE
A negiligible issue: Black bg for text in titlebar

### ISSUE THREAD

**Issue by lostb053** [witalihirsch/qBitTorrent-fluent-theme#20]
It just looks weird, though it's not much of an issue, but would be great if you would fix it

![Screenshot - 25-09-2022 , 19_49_18](https://user-images.githubusercontent.com/72547660/192148436-d20c9664-bacf-4f77-9093-3bc072a15c1d.png)

This shows an active window, the bg becomes gray when inactive.
The theme is really great nevertheless (probably best out there)

Fluent theme version: 2.6
MicaForEveryone version: 1.2.0.1

**Comment by witalihirsch** [comment]
this is a problem with some versions of windows 11, not a theme problem. try installing another version

**Comment by lostb053** [comment]
Yeah, I was going through MicaForEveryone's github page when I noticed same occurrence in some of the screenshots. Sorry for not checking it out first. I guess I will just let it be.
