### ISSUE TITLE
Colored texts for Torrent names and some other bugs

### ISSUE THREAD

**Issue by lostb053** [witalihirsch/qBitTorrent-fluent-theme#21]
I was hoping if you could add colored texts for torrent names where torrents are listed as observed in original/classic qbittorrent theme.
I'm not sure if it fits well with theme. In case it doesn't just comment and close the issue, otherwise I find it quite handy. Green color for active (downloading) torrent, Black for inactive or stalled torrents, Yellow for seeding torrent, Red for errored torrent, Blue for completed torrent. I won't request you to go with same shade as in original, feel free to use other shades that fit better with theme

**Comment by lostb053** [comment]
While you are at it, also check this

![Screenshot - 28-09-2022 , 19_26_05](https://user-images.githubusercontent.com/72547660/192798256-dc797e6a-3411-40f5-a59d-b4c49f40c1e0.png)

Right side of the window shows a black bar but it's actually a black bg with a text in slightly lighter shade of black, making it look almost completely black

**Comment by witalihirsch** [comment]
fixed in no-mica themes

**Comment by lostb053** [comment]
Thanks I'll check it out
By the way, i was also wondering, if you've tried dark-no-mica theme, the title bar (am not sure if that's what we call it, but it's the top bar with three button for minimize, maximize and close) stays white.
I've tried dark mica theme, but i didn't wanted to keep the mica for everyone app (to be honest, it messed with the look and feel of other apps, so when qbittorrent looked totally sexy, other apps were acting weird), so tried using dark no mica one, but then switched to light no mica for dark one still had white titlebar. Is it possible to fix that too?

I'm sorry if I'm being too demanding, but i just can't get enough of your theme. It's too cool

**Comment by lostb053** [comment]
Ahh, ic

**Comment by lostb053** [comment]
Thanx for the theme anyways. It's great

**Comment by lostb053** [comment]
Ok, the issue in 2nd pic has been fixed but not 1st one

**Comment by lostb053** [comment]
I've edited the comment to help fix issue
> **The issue in pic below is fixed** ![Screenshot - 28-09-2022 , 19_33_16](https://user-images.githubusercontent.com/72547660/192800479-b6773983-7fcd-4956-bc25-e8f9d25ad200.png)

**Comment by witalihirsch** [comment]
i've not yet determined how to define these objects

**Comment by lostb053** [comment]
Ic

**Comment by lostb053** [comment]
Yes, this one fixed
But spacing still doesn't make sense to me somehow
I'll send detailed pics later
