### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by onurtore** [witalihirsch/qBitTorrent-fluent-theme#23]
Readme lacks the complete installation guideline for a newbie. Thanks to current version of the README I installed Mica, defined a new rule, change some setting from default to Mica, downloaded the theme, but then I dont know what to do? I have no idea how to use it.

**Comment by lostb053** [comment]
Well, not a dev or a contributor here.
But to install the theme, just go to `Options` (can be found in `Tools`) > `Behaviour` > Check `Use a custom theme` box > Type the path to downloaded theme file in `UI Theme file` or click on folder button and select the theme file

**Comment by witalihirsch** [comment]
fixed
