### ISSUE TITLE
QHeaderView , text not centered

### ISSUE THREAD

**Issue by KrazyLurt** [witalihirsch/qBitTorrent-fluent-theme#3]
adding below in dark.qss solves the issue
`QHeaderView { qproperty-defaultAlignment: AlignVCenter; }`

**Comment by witalihirsch** [comment]
> adding below in dark.qss solves the issue `QHeaderView { qproperty-defaultAlignment: AlignVCenter; }`
it looks a little weird, for some reason not all the text is centered
![align](https://user-images.githubusercontent.com/73841541/172032142-ba482861-2cb9-4554-99d0-e26f76c3159f.gif)

**Comment by KrazyLurt** [comment]
It's nice and centered on my end
![Screenshot 2022-06-05 042723](https://user-images.githubusercontent.com/75538575/172032380-1b57412a-f7ae-4a01-afb7-015fec6f7ba6.png)

I can attach the dark.qss if you like

**Comment by witalihirsch** [comment]
looks great, attach it
do you work with icons?

**Comment by KrazyLurt** [comment]
No not from scratch, I dont a lot of editiing from existing icons, these are from Papirus (gtk theme, linux), and maybe a few from https://github.com/jagannatharjun/qbt-theme.

Please not that the dark.qss have more edits, do a compare in your favorite text editor

`QMainWindow,
QDockWidget {
  background-color: transparent; 
  font-family: "Segoe UI Variable Text";
}

QWidget {
  border-radius: 5px;
  border-color: rgb(255, 255, 255, 8);
  font-size: 12px;
  font-family: "Segoe UI Variable Text";
}

QTabWidget QListView::item {
  padding: 5px; 
}

QTabWidget QListView::item:hover {
  border-radius: 5px;
  background-color: #202833;
  border-color: rgb(255, 255, 255, 0);
}

QTabWidget QListView::item:selected {
  border-radius: 5px;
  outline: 0;
  background-color: #272727;
  border-color: rgb(255, 255, 255, 0);
}

QTabWidget QListWidget::item[Custom="true"]
{
    background: rgb(128,255,128);
}

QObject,
QObject::separator,
QObject::handle,
QObject::tab-bar,
QObject::tab,
QObject::section {
  font-family: "Segoe UI Variable Text";
  margin: 0;
  padding: 0;
  outline: 0;
  border: 0;
  selection-background-color: #26303D;
  selection-color: #FFF;
  alternate-background-color: #292929;
  color: #eee;
  border-radius: 2px; 
}

QDialog,
QWizard *,
QCalendarWidget *,
#qswPages > QObject {
  background-color: transparent;
  color: #d8d8d8; 
}

QAbstractScrollArea {
  background-color: transparent; 
}

QObject:disabled,
QObject::item:disabled {
  color: #fff; 
}

a {
  color: #39a5dd;
  text-decoration: none; 
}

QObject::separator {
  height: 4px;
  width: 4px; 
}

QObject::separator:hover {
  background: #202833; 
}

QToolTip,
QWhatsThis {
  font-size: 8pt;
  min-height: 1.3em;
  border: 1px solid rgb(255, 255, 255, 8);
  border-radius: 5px;
  padding: 3px;
  background-color: #202020;
  color: #ffffff; 
}

QTextBrowser,
QTextEdit {
  background-color: #212121;
  color: #d8d8d8;
  border: 1px solid #1c1c1c; 
}

QToolBar {
  background-color: transparent;
  spacing: 0;
  padding: 7px;
}

QToolButton {
  background-color: rgb(255, 255, 255, 16);
  border: 1px solid rgb(255, 255, 255, 5); 
  border-radius: 7px;
  padding: 1px;
  margin: 1px; 
  margin-left: 5px;
  margin-right: 5px;
}

QToolButton:on {
  background-color: rgb(255, 255, 255, 18);
  border: 1px solid rgb(255, 255, 255, 5); 
}

QToolButton:hover {
  background-color: rgb(255, 255, 255, 20);
  border: 1px solid rgb(255, 255, 255, 5); 
}

QToolButton:pressed {
  background-color: rgb(255, 255, 255, 7);
  border: 1px solid rgb(255, 255, 255, 8);
  color: rgb(255, 255, 255, 200); 
}

QToolBar::separator {
  background: #555;
  height: 1px;
  margin: 4px;
  width: 1px; 
}

QToolBar::separator:hover {
  background: #555;
  border: 0; 
}

QToolButton#qt_toolbar_ext_button {
  min-width: 8px;
  width: 8px;
  padding: 1px;
  qproperty-icon: url(:/uitheme/controls/toolbar_ext.svg); 
}

QToolBar::handle:horizontal {
  image: url(:/uitheme/controls/handle_horizontal.svg);
  width: 8px;
  padding: 4px; 
}

QToolBar::handle:vertical {
  image: url(:/uitheme/controls/handle_vertical.svg);
  height: 8px;
  padding: 4px; 
}

QToolButton::menu-arrow,
QToolButton::menu-indicator,
QPushButton::menu-arrow,
QPushButton::menu-indicator {
  image: url(:/uitheme/controls/arrow_dow.svg);
}

QToolButton[popupMode="1"],
QToolButton[popupMode="2"],
QPushButton[popupMode="1"],
QPushButton[popupMode="2"] {
  padding-right: 14px; 
}

QMenuBar {
    background-color: transparent;
    color: white;
    padding: 5px;
    font-family: "Segoe UI Variable Text", serif;
}

QMenuBar::item {
    background-color: transparent;
    padding: 7px 13px;
    margin-left: 5px;
    border-radius: 5px;
}

QMenuBar::item:selected {
    background-color: rgb(255, 255, 255, 20);
}

QMenuBar::item:pressed {
    background-color: rgb(255, 255, 255, 13);
    color: rgb(255, 255, 255, 200);
}

QMenu {
    background-color: #202020;
    padding-left: 1px;
    padding-top: 1px;
    border: 1px solid rgb(255, 255, 255, 8);
    border-radius: 5px;
}

QHeaderView { qproperty-defaultAlignment: AlignVCenter; }

QMenu::item {
    background-color: transparent;
    padding: 5px 15px;
    border-radius: 5px;
    min-width: 60px;
    margin: 3px;
}

QMenu::item:selected {
    background-color: rgb(255, 255, 255, 16);
}

QMenu::item:pressed {
    background-color: rgb(255, 255, 255, 10);
}

QMenu::right-arrow {
    image: url(:/uitheme/controls/TreeViewClose.png);
    min-width: 40px;
    min-height: 18px;
}

QMenuBar:disabled {
    color: rgb(150, 150, 150);
}

QMenu::item:disabled {
    color: rgb(150, 150, 150);
    background-color: transparent;
}

QPushButton {
  background-color: rgb(255, 255, 255, 18);
  border: 1px solid rgb(255, 255, 255, 5);
  border-radius: 7px;
  color: #d8d8d8;
  padding: 6px 20px; 
}

QPushButton:hover {
  background-color: rgb(255, 255, 255, 25);
  border: 1px solid rgb(255, 255, 255, 10); 
}

QPushButton:pressed,
QPushButton:pressed:focus {
  background-color: rgb(255, 255, 255, 7);
  border: 1px solid rgb(255, 255, 255, 8);
  color: rgb(255, 255, 255, 200);
}

QGroupBox {
  border-radius: 5px;
  border: 1px solid rgb(255, 255, 255, 3);
  margin-top: 30px;
  background-color: rgb(255, 255, 255, 5);
}

QGroupBox::title {
  subcontrol-origin: margin;
  subcontrol-position: top left;
  background-color: rgb(255, 255, 255, 16);
  padding: 7px 15px;
  margin-left: 5px;
  border-top-left-radius: 5px;
  border-top-right-radius: 5px;
}

QGroupBox::title::disabled {
  color: rgb(150, 150, 150)
}

QAbstractItemView {
  alternate-background-color: #292929; }

QListView {
  background-color: #212121;
  border: 1px solid #1c1c1c; }

QListView::item {
  border-radius: 2px;
  border: 1px solid transparent;
  selection-color: #d8d8d8;
  padding: 2px 4px; }

QListView::item:hover {
  background-color: #202833;
  border: 1px solid #333; }

QListView::item:selected {
  background-color: #3b3b3b;
  border: 1px solid #3b3b3b; }

QListView::item:selected:active {
  background-color: #3e4f5e;
  border: 1px solid #3e4f5e; }

QTreeView {
  background-color: transparent;
  color: white;
  selection-background-color: #212121;
  selection-color: #d8d8d8;
  border: 1px solid transparent; 
  outline: 0;
}

QTreeView::item {
  min-width: 60px;
  border: 1px solid transparent;
  border-left: 0;
  border-right: 0;
  padding: 2px 4px;
  selection-color: #fff;
  border-radius: 0; 
  outline: 0;
}

QTreeView::item:first,
QTreeView::item:only-one {
  border-left: 1px solid transparent;
  border-top-left-radius: 2px;
  border-bottom-left-radius: 2px; }

QTreeView::item:last,
QTreeView::item:only-one {
  border-right: 1px solid transparent;
  border-top-right-radius: 2px;
  border-bottom-right-radius: 2px; }

QTreeView::item:hover,
QTreeView::item:focus {
  background-color: #202833;
  border-color: #333; }

QTreeView::item:selected {
  background-color: #202833;
  border: 1px solid #3b3b3b;
  border-right: 0;
  border-left: 0; }

QTreeView::item:selected:first,
QTreeView::item:selected:only-one {
  border-left: 1px solid #3b3b3b; }

QTreeView::item:selected:last,
QTreeView::item:selected:only-one {
  border-right: 1px solid #3b3b3b; }

QTreeView::item:selected:active {
  background-color: #202833;
  border: 1px solid #3e4f5e;
  border-right: 0;
  border-left: 0; }

QTreeView::item:selected:active:first,
QTreeView::item:selected:active:only-one {
  border-left: 1px solid #3e4f5e; }

QTreeView::item:selected:active:last,
QTreeView::item:selected:active:only-one {
  border-right: 1px solid #3e4f5e; }

QTreeView::branch {
  border-image: none;
  image: none;
  margin-left: 3px;
  margin-top: 1px;
  padding-left: 3px; }

QTreeView::branch:has-children:closed {
  image: url(:/uitheme/controls/TreeViewClose.png); }

QTreeView::branch:has-children:open {
  image: url(:/uitheme/controls/TreeViewOpen.png); }

QHeaderView {
  border-radius: 5;
  background-color: transparent; 
  text-align: center;
}

QHeaderView::section {
  background-color: rgb(255, 255, 255, 8);
  color: #d8d8d8;
  padding: 4px;
  padding-left: 8px;
  padding-right: 20px;
  border-radius: 0;
}

QHeaderView::section:first {
  border-top-left-radius: 5px;
}

QHeaderView::section:last {
  border-top-right-radius: 5px;
}

QHeaderView::section:hover:first {
  border-top-left-radius: 5px;
}

QHeaderView::section:hover:last {
  border-top-right-radius: 5px;
}

QHeaderView::section:hover {
  background-color: rgb(255, 255, 255, 12);
}

QHeaderView::down-arrow,
QHeaderView::up-arrow {
  margin: 1px;
  top: 1px;
  right: 5px;
  width: 14px; 
}

QHeaderView::down-arrow {
  image: url(:/uitheme/controls/arrow_dow.svg); 
}

QHeaderView::up-arrow {
  image: url(:/uitheme/controls/arrow_u.svg); 
}

QTabWidget {
}

QTabWidget::pane {
  border: 0px solid rgb(255, 255, 255, 40);
  border-radius: 5px;
}

QTabWidget::tab-bar {
  left: 15px;
}

QTabBar::tab {
  background-color: rgb(255, 255, 255, 0);
  padding: 7px 15px;
  margin-right: 2px;
  margin-bottom: 2px;
}

QTabBar::tab:hover {
  background-color: rgb(255, 255, 255, 13);
  border-radius: 7px;
}

QTabBar::tab:selected {
  background-color: rgb(255, 255, 255, 16);
  border-radius: 7px;
}

QTabBar::tab:disabled {
  color: rgb(150, 150, 150)
}

/*SCROLLVERTICAL*/
QScrollBar:vertical {
    border: 6px solid rgb(255, 255, 255, 0);
    background-color: transparent;
    margin: 0px 0px 0px 0px;
    width: 16px;
}

QScrollBar:vertical:hover {
    border: 5px solid rgb(255, 255, 255, 0);
}

QScrollBar::handle:vertical {
    background-color: rgb(255, 255, 255, 130);
    border-radius: 2px;
    min-height: 25px;
}

QScrollBar::sub-line:vertical {
    image: url(:/uitheme/controls/ScrollTop.png);
    subcontrol-position: top;
    subcontrol-origin: margin;
}

QScrollBar::sub-line:vertical:hover {
    image: url(:/uitheme/controls/ScrollTopHover.png);
}

QScrollBar::sub-line:vertical:pressed {
    image: url(:/uitheme/controls/ScrollTopPressed.png);
}

QScrollBar::add-line:vertical {
    image: url(:/uitheme/controls/ScrollBottom.png);
    subcontrol-position: bottom;
    subcontrol-origin: margin;
}

QScrollBar::add-line:vertical:hover {
    image: url(:/uitheme/controls/ScrollBottomHover.png);
}

QScrollBar::add-line:vertical:pressed {
    image: url(:/uitheme/controls/ScrollBottomPressed.png);
}

QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {
    background: none;
}

/*SCROLLHORIZONTAL*/
QScrollBar:horizontal {
    border: 6px solid rgb(255, 255, 255, 0);
    background-color: transparent;
    margin: 0px 0px 0px 0px;
    height: 16px;
}

QScrollBar:horizontal:hover {
    border: 5px solid rgb(255, 255, 255, 0);
}

QScrollBar::handle:horizontal {
    background-color: rgb(255, 255, 255, 130);
    border-radius: 2px;
    min-width: 25px;
}

QScrollBar::sub-line:horizontal {
    image: url(:/uitheme/controls/ScrollLeft.png);
    subcontrol-position: left;
    subcontrol-origin: margin;
}

QScrollBar::sub-line:horizontal:hover {
    image: url(:/uitheme/controls/ScrollLeftHover.png);
}

QScrollBar::sub-line:horizontal:pressed {
    image: url(:/uitheme/controls/ScrollLeftPressed.png);
}

QScrollBar::add-line:horizontal {
    image: url(:/uitheme/controls/ScrollRight.png);
    subcontrol-position: right;
    subcontrol-origin: margin;
}

QScrollBar::add-line:horizontal:hover {
    image: url(:/uitheme/controls/ScrollRightHover.png);
}

QScrollBar::add-line:horizontal:pressed {
    image: url(:/uitheme/controls/ScrollRightPressed.png);
}

QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {
    background: none;
}

QAbstractScrollArea::corner {
  border-left: 1px solid transparent;
  border-top: 1px solid transparent;
  height: 0;
  width: 0;
  border-radius: 0;
  border-top: 1px solid transparent;
  border-left: 1px solid transparent;
  background: #212121; }

QRadioButton::indicator {
  background: #444;
  border: 1px solid #444;
  border-radius: 7px;
  height: 12px;
  width: 12px; }

QTreeView::indicator {
  background: #444; }

QProgressBar:horizontal {
  text-align: center; }

QProgressBar {
  background-color: rgb(255, 255, 255, 16);
  border-radius: 5px;
}

QSpinBox {
    background-color: rgb(255, 255, 255, 10);
    border: 1px solid rgb(255, 255, 255, 8);
    border-radius: 5px;
    padding-left: 10px;
    min-height: 28px;
    max-height: 28px;
    min-width: 90px;
    border-bottom: 1px solid #707070;
}

QSpinBox:hover {
    background-color: rgb(255, 255, 255, 16);
    border: 1px solid rgb(255, 255, 255, 10);
    border-bottom: 1px solid #707070;
}

QSpinBox::focus {
    background-color: rgb(255, 255, 255, 5);
    border: 1px solid rgb(255, 255, 255, 8);
    color: rgb(255, 255, 255, 200);
    border-bottom: 2px solid #4cc2ff;
}

QSpinBox::up-button {
    image: url(:/uitheme/controls/SpinBoxUp.png);
    background-color: rgb(0, 0, 0, 0);
    border: 1px solid rgb(0, 0, 0, 0);
    border-radius: 4px;
    margin-top: 1px;
    margin-bottom: 1px;
    margin-right: 3px;
    min-width: 25px;
    max-width: 25px;
    min-height: 15px;
}

QSpinBox::up-button:hover {
    background-color: rgb(255, 255, 255, 13);
}

QSpinBox::up-button:pressed {
    background-color: rgb(255, 255, 255, 5);
}

QSpinBox::down-button {
    image: url(:/uitheme/controls/SpinBoxDown.png);
    background-color: rgb(0, 0, 0, 0);
    border: 1px solid rgb(0, 0, 0, 0);
    border-radius: 4px;
    margin-top: 1px;
    margin-bottom: 1px;
    margin-right: 3px;
    min-width: 25px;
    max-width: 25px;
    min-height: 15px;
}

QSpinBox::down-button:hover {
    background-color: rgb(255, 255, 255, 13);
}

QSpinBox::down-button:pressed {
    background-color: rgb(255, 255, 255, 5);
}

QSpinBox::drop-down {
    background-color: transparent;
    width: 50px;
}

QSpinBox:disabled {
    color: rgb(150, 150, 150);
    background-color: rgb(255, 255, 255, 13);
    border: 1px solid rgb(255, 255, 255, 5);
}

QSpinBox::up-button:disabled {
    image: url(:/uitheme/controls/SpinBoxUpDisabled.png);
}

QSpinBox::down-button:disabled {
    image: url(:/uitheme/controls/SpinBoxDownDisabled.png);
}

QDoubleSpinBox {
    background-color: rgb(255, 255, 255, 10);
    border: 1px solid rgb(255, 255, 255, 13);
    border-radius: 5px;
    padding-left: 10px;
    min-height: 28px;
    max-height: 28px;
    min-width: 90px;
    border-bottom: 1px solid #707070;
}

QDoubleSpinBox:hover {
    background-color: rgb(255, 255, 255, 16);
    border: 1px solid rgb(255, 255, 255, 13);
    border-bottom: 1px solid #707070;
}

QDoubleSpinBox::focus {
    background-color: rgb(255, 255, 255, 5);
    border: 1px solid rgb(255, 255, 255, 13);
    color: rgb(255, 255, 255, 200);
    border-bottom: 2px solid #4cc2ff;
}

QDoubleSpinBox::up-button {
    image: url(:/uitheme/controls/SpinBoxUp.png);
    background-color: rgb(0, 0, 0, 0);
    border: 1px solid rgb(0, 0, 0, 0);
    border-radius: 4px;
    margin-top: 1px;
    margin-bottom: 1px;
    margin-right: 3px;
    min-width: 25px;
    max-width: 25px;
    min-height: 15px;
}

QDoubleSpinBox::up-button:hover {
    background-color: rgb(255, 255, 255, 13);
}

QDoubleSpinBox::up-button:pressed {
    background-color: rgb(255, 255, 255, 5);
}

QDoubleSpinBox::down-button {
    image: url(:/uitheme/controls/SpinBoxDown.png);
    background-color: rgb(0, 0, 0, 0);
    border: 1px solid rgb(0, 0, 0, 0);
    border-radius: 4px;
    margin-top: 1px;
    margin-bottom: 1px;
    margin-right: 3px;
    min-width: 25px;
    max-width: 25px;
    min-height: 15px;
}

QDoubleSpinBox::down-button:hover {
    background-color: rgb(255, 255, 255, 13);
}

QDoubleSpinBox::down-button:pressed {
    background-color: rgb(255, 255, 255, 5);
}

QDoubleSpinBox::drop-down {
    background-color: transparent;
    width: 50px;
}

QDoubleSpinBox:disabled {
    color: rgb(150, 150, 150);
    background-color: rgb(255, 255, 255, 13);
    border: 1px solid rgb(255, 255, 255, 5);
}

QDoubleSpinBox::up-button:disabled {
    image: url(:/uitheme/controls/SpinBoxUpDisabled.png);
}

QDoubleSpinBox::down-button:disabled {
    image: url(:/uitheme/controls/SpinBoxDownDisabled.png);
}

QDateTimeEdit {
    background-color: rgb(255, 255, 255, 10);
    border: 1px solid rgb(255, 255, 255, 13);
    border-radius: 5px;
    padding-left: 10px;
    min-height: 26px;
    max-height: 26px;
    min-width: 80px;
    border-bottom: 1px solid #707070;
}

QDateTimeEdit:hover {
    background-color: rgb(255, 255, 255, 16);
    border: 1px solid rgb(255, 255, 255, 13);
    border-bottom: 1px solid #707070;
}

QDateTimeEdit::focus {
    background-color: rgb(255, 255, 255, 5);
    border: 1px solid rgb(255, 255, 255, 13);
    color: rgb(255, 255, 255, 200);
    border-bottom: 2px solid #707070;
}

QDateTimeEdit::up-button {
    image: url(:/uitheme/controls/SpinBoxUp.png);
    background-color: rgb(0, 0, 0, 0);
    border: 1px solid rgb(0, 0, 0, 0);
    border-radius: 4px;
    margin-top: 1px;
    margin-bottom: 1px;
    margin-right: 2px;
    min-width: 25px;
    max-width: 25px;
    min-height: 15px;
}

QDateTimeEdit::up-button:hover {
    background-color: rgb(255, 255, 255, 13);
}

QDateTimeEdit::up-button:pressed {
    background-color: rgb(255, 255, 255, 5);
}

QDateTimeEdit::down-button {
    image: url(:/uitheme/controls/SpinBoxDown.png);
    background-color: rgb(0, 0, 0, 0);
    border: 1px solid rgb(0, 0, 0, 0);
    border-radius: 4px;
    margin-top: 1px;
    margin-bottom: 1px;
    margin-right: 2px;
    min-width: 25px;
    max-width: 25px;
    min-height: 15px;
}

QDateTimeEdit::down-button:hover {
    background-color: rgb(255, 255, 255, 13);
}

QDateTimeEdit::down-button:pressed {
    background-color: rgb(255, 255, 255, 5);
}

QDateTimeEdit::drop-down {
    background-color: transparent;
    width: 50px;
}

QDateTimeEdit:disabled {
    color: rgb(150, 150, 150);
    background-color: rgb(255, 255, 255, 13);
    border: 1px solid rgb(255, 255, 255, 5);
}

QDateTimeEdit::up-button:disabled {
    image: url(:/uitheme/controls/SpinBoxUpDisabled.png);
}

QDateTimeEdit::down-button:disabled {
    image: url(:/uitheme/controls/SpinBoxDownDisabled.png);
}

QComboBox {
    background-color: rgb(255, 255, 255, 10);
    border: 1px solid rgb(255, 255, 255, 5);
    border-radius: 5px;
    padding-left: 10px;
    min-height: 29px;
    max-height: 29px;
}

QComboBox:hover {
    background-color: rgb(255, 255, 255, 16);
    border: 1px solid rgb(255, 255, 255, 7);
}

QComboBox::down-arrow {
    image: url(:/uitheme/controls/ComboBox.png);
    width: 40px;
    height: 40px;
    margin-left: 15px;
}

QComboBox::drop-down {
    background-color: transparent;
    min-width: 50px;
}

QComboBox:disabled {
    color: rgb(150, 150, 150);
    background-color: rgb(255, 255, 255, 13);
    border: 1px solid rgb(255, 255, 255, 5);
}

QComboBox::down-arrow:disabled {
    image: url(:/uitheme/controls/ComboBoxDisabled.png);
}

QCheckBox {
    min-height: 20px;
    max-height: 20px;
}

QGroupBox::indicator,
QMenu::indicator,
QCheckBox::indicator {
    width: 13px;
    height: 13px;
    border-radius: 4px;
    border: 1px solid #606060;
    background-color: rgb(255, 255, 255, 0);
    margin-right: 5px;
}

QGroupBox::indicator:hover,
QMenu::indicator:hover,
QCheckBox::indicator:hover {
    background-color: rgb(255, 255, 255, 16);
}

QGroupBox::indicator:checked:hover,
QMenu::indicator:checked:hover,
QCheckBox::indicator:checked:hover {
    background-color: #47b1e8;
}

QGroupBox::indicator:pressed,
QMenu::indicator:pressed,
QCheckBox::indicator:pressed {
    background-color: rgb(255, 255, 255, 20);
    border: 1px solid #434343;
}

QGroupBox::indicator:checked,
QMenu::indicator:checked,
QCheckBox::indicator:checked {
    background-color: #4cc2ff;
    border: 1px solid #4cc2ff;
    image: url(:/uitheme/controls/CheckBox.png);
}

QMenu::indicator:checked:pressed,
QCheckBox::indicator:checked:pressed {
    image: url(:/uitheme/controls/CheckBoxPressed.png);
}

QCheckBox:disabled {
    color: rgb(150, 150, 150);
}

QMenu::indicator:disabled,
QCheckBox::indicator:disabled {
    border: 1px solid #555555;
    background-color: rgb(255, 255, 255, 0);
}

QLabel,
QCheckBox,
QAbstractCheckBox,
QTreeView::indicator,
QRadioButton {
  min-height: 20px;
  max-height: 20px; 
}

QCheckBox::indicator,
QTreeView::indicator {
  width: 13px;
  height: 13px;
  border-radius: 4px;
  border: 1px solid #606060;
  background-color: rgb(255, 255, 255, 0);
  margin-right: 5px;
}

QTreeView::indicator {
  margin: .4em; }

QMenu::indicator {
  left: 6px; }

QCheckBox::indicator:pressed,
QMenu::indicator:pressed,
QTreeView::indicator:pressed {
  background-color: rgb(255, 255, 255, 20);
  border: 1px solid #434343;
}

QCheckBox::indicator:checked,
QMenu::indicator:checked,
QTreeView::indicator:checked {
  background-color: #4cc2ff;
  border: 1px solid #4cc2ff;
  image: url(:/uitheme/controls/CheckBox.png); 
}

QCheckBox::indicator:checked:pressed,
QMenu::indicator:checked:pressed,
QTreeView::indicator:checked:pressed,
QGroupBox::indicator:checked:pressed {
  image: url(:/uitheme/controls/CheckBoxPressed.png);
}

QCheckBox::indicator:disabled,
QTreeView::indicator:disabled {
  border: 1px solid #646464;
  background-color: rgb(255, 255, 255, 0); 
}

QCheckBox::indicator:checked:disabled,
QTreeView::indicator:checked:disabled {
  border: 1px solid #555555;
  image: url(:/uitheme/controls/CheckBoxPressed.png); 
}

QTextEdit {
  background-color: rgb(255, 255, 255, 16);
  border: 1px solid rgb(255, 255, 255, 5);
  font-size: 16px;
  font-family: "Segoe UI Variable Text", serif;
  font-weight: 500;
  border-radius: 7px;
  border-bottom: 1px solid #707070;
  padding: 5px;
}

QTextEdit:hover {
  background-color: rgb(255, 255, 255, 20);
  border: 1px solid rgb(255, 255, 255, 10);
  border-bottom: 1px solid #707070;
}

QTextEdit:focus {
  border-bottom: 2px solid #4cc2ff;
  background-color: rgb(255, 255, 255, 5);
  border-top: 1px solid rgb(255, 255, 255, 7);
  border-left: 1px solid rgb(255, 255, 255, 7);
  border-right: 1px solid rgb(255, 255, 255, 7);
}

QTextEdit:disabled {
  color: rgb(150, 150, 150);
  background-color: rgb(255, 255, 255, 13);
  border: 1px solid rgb(255, 255, 255, 5);
}

QLineEdit {
  background-color: rgb(255, 255, 255, 16);
  border: 1px solid rgb(255, 255, 255, 5);
  font-family: "Segoe UI Variable Text", serif;
  border-radius: 7px;
  border-bottom: 1px solid #707070;
  padding-left: 5px;
  padding-top: 4px;
  padding-bottom: 4px;
}

QLineEdit:hover {
  background-color: rgb(255, 255, 255, 20);
  border: 1px solid rgb(255, 255, 255, 10);
  border-bottom: 1px solid #707070;
}

QLineEdit:focus {
  border-bottom: 2px solid #4cc2ff;
  background-color: rgb(255, 255, 255, 5);
  border-top: 1px solid rgb(255, 255, 255, 7);
  border-left: 1px solid rgb(255, 255, 255, 7);
  border-right: 1px solid rgb(255, 255, 255, 7);
}

QLineEdit:disabled {
  color: rgb(150, 150, 150);
  background-color: rgb(255, 255, 255, 13);
  border: 1px solid rgb(255, 255, 255, 5);
}

QLineEdit
QToolButton {
  background-color: transparent;
}

QLineEdit:hover
QToolButton:hover {
  background-color: transparent;
}

QLineEdit:pressed
QToolButton:pressed {
  background-color: transparent;
}

QRadioButton {
  min-height: 30px;
  max-height: 30px;
}

QRadioButton::indicator {
  width: 22px;
  height: 22px;
  border-radius: 13px;
  border: 2px solid #848484;
  background-color: rgb(255, 255, 255, 0);
  margin-right: 5px;
}

QRadioButton::indicator:hover {
  background-color: rgb(255, 255, 255, 16);
}

QRadioButton::indicator:pressed {
  background-color: rgb(255, 255, 255, 20);
  border: 2px solid #434343;
  image: url(:/uitheme/controls/RadioButton.png);
}

QRadioButton::indicator:checked {
  background-color: blue;
  border: 2px solid blue;
  image: url(:/uitheme/controls/RadioButton.png);
}

QRadioButton::indicator:checked:hover {
  image: url(:/uitheme/controls/RadioButtonHover.png);
}

QRadioButton::indicator:checked:pressed {
  image: url(:/uitheme/controls/RadioButtonPressed.png);
}

QRadioButton:disabled {
  color: rgb(150, 150, 150);
}

QRadioButton::indicator:disabled {
  border: 2px solid #646464;
  background-color: rgb(255, 255, 255, 0);
}

QSlider:vertical {
  min-width: 30px;
  min-height: 100px;
}

QSlider::groove:vertical {
  width: 5px; 
  background-color: rgb(255, 255, 255, 150);
  border-radius: 2px;
  padding-top: -1px;
  padding-bottom: -1px;
}

QSlider::handle:vertical {
  background-color: #4cc2ff;
  border: 4px solid #454545;
  height: 9px;
  min-width: 13px;
  margin: 0px -7px;
  border-radius: 8px
}

QSlider::handle:vertical:hover {
  background-color: #4cc2ff;
  border: 3px solid #454545;
  height: 11px;
  min-width: 13px;
  margin: 0px -7px;
  border-radius: 8px
}

QSlider::handle:vertical:pressed {
  background-color: #4cc2ff;
  border: 5px solid #454545;
  height: 7px;
  min-width: 13px;
  margin: 0px -7px;
  border-radius: 8px
}

QSlider::groove:vertical:disabled {
  background-color: rgb(255, 255, 255, 75);
}

QSlider::handle:vertical:disabled {
  background-color: #555555;
  border: 6px solid #353535;
}

/*SLIDERHORIZONTAL*/
QSlider:horizontal {
  min-width: 100px;
  min-height: 30px;
}

QSlider::groove:horizontal {
  height: 3px; 
  background-color: rgb(255, 255, 255, 150);
  border-radius: 1px;
  padding-left: -1px;
  padding-right: -1px;
}

QSlider::handle:horizontal {
  background-color: #4cc2ff;
  border: 4px solid #454545;
  width: 9px;
  min-height: 13px;
  margin: -7px 0;
  border-radius: 8px
}

QSlider::handle:horizontal:hover {
  background-color: #4cc2ff;
  border: 3px solid #454545;
  width: 11px;
  min-height: 13px;
  margin: -7px 0;
  border-radius: 8px
}

QSlider::handle:horizontal:pressed {
  background-color: #4cc2ff;
  border: 5px solid #454545;
  width: 7px;
  min-height: 13px;
  margin: -7px 0;
  border-radius: 8px
}

QSlider::groove:horizontal:disabled {
  background-color: rgb(255, 255, 255, 75);
}

QSlider::handle:horizontal:disabled {
  background-color: #555555;
  border: 6px solid #353535;
}

QFontDialog {
  min-width: 32em;
  min-height: 24em; }

QColorDialog QColorLuminancePicker {
  background-color: transparent; }

QMessageBox,
QDialogButtonBox {
  dialogbuttonbox-buttons-have-icons: 0; }

/* Mumble Specifics */
LogTextBrowser,
#qdsChat {
  margin: 0 2px;
  min-height: 120px;
  min-width: 40px;
  border-color: #1c1c1c; }

UserView {
  margin: 0 2px;
  min-height: 120px;
  min-width: 40px; }

UserView::item {
  padding: 0;
  padding-top: -1px; }

#qdwChat > QTextEdit {
  padding: -2px;
  margin: 0 2px;
  margin-bottom: 2px; }

.log-time {
  background-color: transparent;
  color: #95a5a6; }

.log-server {
  background-color: transparent;
  color: #F9655D;
  font-weight: bold; }

.log-channel {
  background-color: transparent;
  color: #e67e22;
  font-weight: bold; }

.log-privilege {
  background-color: transparent;
  color: #c0392b;
  font-weight: bold; }

.log-target {
  background-color: transparent;
  color: #27ae60;
  font-weight: bold; }

.log-source {
  background-color: transparent;
  color: #27ae60;
  font-weight: bold; }

QSlider {
  margin-left: 30px;
  margin-right: 30px; }

#qswPages > * > * > QScrollBar {
  margin: 0; }

#qswPages > * > QWidget {
  margin: 2px; }

AboutDialog > QTextBrowser,
AboutDialog QTextEdit {
  border: 0; }

#qtbToolBar {
  border: 1px solid transparent;
  background: transparent; }

#BanEditor {
  min-width: 600px; }

#GlobalShortcutTarget {
  min-height: 600px; }

ViewCert {
  min-height: 600px; }

TransferListWidget {
  qproperty-downloadingStateForeground: limegreen;
  qproperty-forcedDownloadingStateForeground: limegreen;
  qproperty-downloadingMetadataStateForeground: limegreen;
  qproperty-allocatingStateForeground: #cccccc;
  qproperty-stalledDownloadingStateForeground: #cccccc;
  qproperty-stalledUploadingStateForeground: #cccccc;
  qproperty-uploadingStateForeground: #63b8ff;
  qproperty-forcedUploadingStateForeground: #63b8ff;
  qproperty-pausedDownloadingStateForeground: #fa8090;
  qproperty-pausedUploadingStateForeground: #4f94cd;
  qproperty-errorStateForeground: red;
  qproperty-missingFilesStateForeground: red;
  qproperty-queuedDownloadingStateForeground: #00cdcd;
  qproperty-queuedUploadingStateForeground: #00cdcd;
  qproperty-checkingDownloadingStateForeground: #00cdcd;
  qproperty-checkingUploadingStateForeground: #00cdcd;
  qproperty-checkingResumeDataStateForeground: #00cdcd;
  qproperty-movingStateForeground: #00cdcd;
  qproperty-unknownStateForeground: red; }
`

**Comment by witalihirsch** [comment]
can you send the whole project with icons?

**Comment by KrazyLurt** [comment]
https://drive.google.com/file/d/1bljqABdpSQVdRiZQCaBPes5ZADzPkuno/view?usp=sharing

I'll upload and link it to my Google Drive.
Please note that I have made a few more adjustments like padding, more
transparent bits, size of message boxes that had a few issues.

**Comment by KrazyLurt** [comment]
use this link instead

https://drive.google.com/file/d/1JZxBeuvvxmn7X8JUkzs3GhfvNdm4Mbcd/view?usp=sharing

**Comment by KrazyLurt** [comment]
Yay, that looks really nice , good job! 😀
