### ISSUE TITLE
qBittorrent 4.5.0 breaks columns spacing

### ISSUE THREAD

**Issue by ararezaee** [witalihirsch/qBitTorrent-fluent-theme#30]
You cant reduce column size after a certain point therefor there will be a lot of empty space left

**Comment by darkj2k** [comment]
I think this issue belong qBittorrent 4.5.0. 4.4.5 has no such issue.

**Comment by ararezaee** [comment]
> I think this issue belong qBittorrent 4.5.0. 4.4.5 has no such issue.

4.5.0 have made some changes in their UI but it doesn't have this specific issue on its default skin. Most likely they have made some api/flag or so on changes that need to be updated in 3rd party skins.

**Comment by witalihirsch** [comment]
I updated the client and didn't realize what you're talking about, please send a screenshot

**Comment by ararezaee** [comment]
![Untitled](https://user-images.githubusercontent.com/24833434/205621199-37a6de00-de72-404f-bb50-5a9c176e640e.jpg)
 
For example you can't make the "#" bar any smaller than this

**Comment by lostb053** [comment]
Exactly

**Comment by lostb053** [comment]
What's even weirder is, u can't make it any smaller, but at its smallest, text for some columns is on right, for others on left

**Comment by ararezaee** [comment]
> What's even weirder is, u can't make it any smaller, but at its smallest, text for some columns is on right, for others on left

Yes you are right there is an alignment issue as well.

**Comment by lostb053** [comment]
though it's not a big deal, looks cool anyways, but makes it hard to arrange it

**Comment by witalihirsch** [comment]
yes, I also remember this bug in the versions below. I'll fix it a bit later

**Comment by lostb053** [comment]
No worries, that last update made theme complete for me
Minor improvements needed, no big deal

**Comment by ararezaee** [comment]
> yes, I also remember this bug in the versions below. I'll fix it a bit later

That would be great, I can't imagine this theme would need anything more after these two bug fixes. Pretty much perfect.

**Comment by witalihirsch** [comment]
> What's even weirder is, u can't make it any smaller, but at its smallest, text for some columns is on right, for others on left

I thought how to fix it, but in fact this is already a problem with the location of objects in the app itself and I cannot change them

**Comment by witalihirsch** [comment]
guys, I don't see a problem. seems to be exactly the same without a theme. can you show how it looks like for you?
![align](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif)

**Comment by lostb053** [comment]
> > What's even weirder is, u can't make it any smaller, but at its smallest, text for some columns is on right, for others on left
> 
> I thought how to fix it, but in fact this is already a problem with the location of objects in the app itself and I cannot change them

Ok, no worries i guess.
But i won't be able to try the theme anytime soon.
I'll comment on this later

**Comment by ararezaee** [comment]
Apologizes for my tardiness, I was unable to test the new update till today

I have found out that the issue I brought up is somehow related to qBittorrent itself not the theme. I am currently using this theme on my main PC and all the columns are adjustable on the other hand I have another PC where qBittorent is running without any themes and I have the same issue on it, so that means its a bug within the actual software.

Thanks for everything.

**Comment by lostb053** [comment]
> guys, I don't see a problem. seems to be exactly the same without a theme. can you show how it looks like for you? ![align](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif) [ ![align](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif) ](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif) [ ](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif)

Mind if i ask which version off client u using?
I'll try on same version later

**Comment by lostb053** [comment]
qt version?

> > > guys, I don't see a problem. seems to be exactly the same without a theme. can you show how it looks like for you? ![align](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif)
> > >       
> > >         [
> > >           
> > >             ![align](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif)
> > >           
> > >         ](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif)
> > 
> > 
> > Mind if i ask which version off client u using?
> > I'll try on same version later
> 
> Yep, I'm using 4.5.0

**Comment by witalihirsch** [comment]
> qt version?
> 
> 
> 
> > > > guys, I don't see a problem. seems to be exactly the same without a theme. can you show how it looks like for you? ![align](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif)
> 
> > > >       
> 
> > > >         [
> 
> > > >           
> 
> > > >             ![align](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif)
> 
> > > >           
> 
> > > >         ](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif)
> 
> > > >         
> 
> > > >         
> 
> > > >           
> 
> > > >             
> 
> > > >               
> 
> > > >             
> 
> > > >             
> 
> > > >               
> 
> > > >               
> 
> > > >             
> 
> > > >           
> 
> > > >           [
> 
> > > >             
> 
> > > >               
> 
> > > >             
> 
> > > >           ](https://user-images.githubusercontent.com/73841541/209523283-7567e663-802e-4cd3-8c68-00fca9a41813.gif)
> 
> > > 
> 
> > > 
> 
> > > Mind if i ask which version off client u using?
> 
> > > I'll try on same version later
> 
> > 
> 
> > Yep, I'm using 4.5.0
> 
> 
> 
> 

Qt6

**Comment by 3aTi3** [comment]
I have the same issue, qBittorrent 4.5.5 qt6 lt20 (but was the same with 4.5.2). Windows 11, Dark theme -with or without Mica.
Disabling the Custom theme will revert to the correct column spacing.

![image](https://github.com/witalihirsch/qBitTorrent-fluent-theme/assets/147758910/9e191766-c2ff-4c3f-a996-504517ae9a94)
