### ISSUE TITLE
Bland Icons

### ISSUE THREAD

**Issue by ArtexJay** [witalihirsch/qBitTorrent-fluent-theme#32]
Love the theme honestly, however the monochrome icons look bland and boring to me after using Qbittorrent with their newer colorful icons. Would it be at all possible to use the default icons on qbittorrent rather the monochrome ones or to use a colored variant of the monochrome icons you currently have in your theme?

![image](https://user-images.githubusercontent.com/32932497/208849218-360111c1-d300-4306-a18b-5e777f993d5c.png)
![image](https://user-images.githubusercontent.com/32932497/208849594-32425a6d-6f7d-4621-9a5b-3525b93aa5cc.png)

**Comment by witalihirsch** [comment]
yep, you should to download source code. go to `Builds` and delete `icons` folder. Run `.bat` file in the same directory and you will see new `qbtheme` file

**Comment by GitExploraa** [comment]
> yep, you should to download source code. go to `Builds` and

I did exactly what you described but couldnt find the resulting file anywhere... any idea?

**Comment by rangan2510** [comment]
Open a terminal window and then run the bat file. In that case, you can see any errors that are happening. Errors could be most likely because of missing dependencies. Install them and it will work fine. You need to have the build tools in order to be able to make the build. Ensure that once then let us know here!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by witalihirsch** [comment]
> > yep, you should to download source code. go to `Builds` and
> 
> 
> 
> I did exactly what you described but couldnt find the resulting file anywhere... any idea?

My fault, try to delete not the folder, remove all files inside dark and light folders

**Comment by GitExploraa** [comment]
> > > yep, you should to download source code. go to `Builds` and
> > 
> > 
> > I did exactly what you described but couldnt find the resulting file anywhere... any idea?
> 
> My fault, try to delete not the folder, remove all files inside dark and light folders

still dont get it sorry, guess ill just wait for the app to (maybe) get updated or use it just as it is

**Comment by witalihirsch** [comment]
I created a new release with default icons, but maybe in the future, when I can configure icons for all objects, I'll return to fluent icons

**Comment by ArtexJay** [comment]
> I created a new release with default icons, but maybe in the future, when I can configure icons for all objects, I'll return to fluent icons

I wouldn't mind the return to fluent icons if they are colored, personally.

**Comment by GitExploraa** [comment]
> I created a new release with default icons, but maybe in the future, when I can configure icons for all objects, I'll return to fluent icons

Perfect, Thanks a lot
