### ISSUE TITLE
Hover Selector with Mica

### ISSUE THREAD

**Issue by ArtexJay** [witalihirsch/qBitTorrent-fluent-theme#33]
When hovering over a torrent, is a bit hard to see the highlight, by contrast the sidebar hover/selected highlight is a bit more visible. I think it would be better if both of them would use the similar brightness or color contrast that the buttons like "general, trackers, peers, etc" use, they are the easiest to spot with mica on.
Side note it appears that the sidebar and the torrent list also use different colors to highlight when hovering.

![image](https://user-images.githubusercontent.com/32932497/209576985-806bc911-ab32-4bd7-9f1a-da9e2df5e957.png)
![image](https://user-images.githubusercontent.com/32932497/209577124-bd534bd4-ae7f-44bb-8af2-3172038212e5.png)

**Comment by ArtexJay** [comment]
turns out i had "Mica Tabbed" enabled by accident in the Mica Everywhere which made everything darker. Reverting it to "Mica" seems to have fixed the "hard to see"
So, i guess my suggested change can still apply to make some parts a bit more visible when using "Mica Tabbed" or at least unify the hover highlight color a bit more. Column hover appears to be #2b2b2b, Torrent hover appears to be #272727 without Mica on the Mica enabled theme.
If not then this issue can be closed.

**Comment by ArtexJay** [comment]
Accidentally hit close, I think unifying the hover highlight or making it a bit more visible would be good.

**Comment by witalihirsch** [comment]
fixed, I think now it should be visible well
