### ISSUE TITLE
some context menu items (text) are not aligned

### ISSUE THREAD

**Issue by b-user** [witalihirsch/qBitTorrent-fluent-theme#34]
right-click on the torrent that has not been downloaded yet

![fluent-light-no-mica-1](https://user-images.githubusercontent.com/11581901/210226281-43cfe5e2-8603-49d2-bb12-7b4e44662805.png)

**Comment by witalihirsch** [comment]
I know about this problem, but I don't know how to fix it

**Comment by witalihirsch** [comment]
I tried to fix it but couldn't, most likely these popup elements after downloading torrents have completely different properties, but I don't have that much time to figure it out right now. if you find a solution then you can open a new issue

**Comment by nathnaeld** [comment]
This might be due to missing leading icons for context menu items.
