### ISSUE TITLE
Letters and Icons Issue

### ISSUE THREAD

**Issue by AP-VX** [witalihirsch/qBitTorrent-fluent-theme#36]
With the issue provided, I tried a test to check the problem - trying to change the font face in the qss file and rebuilding the theme, regardless to say my font issue got solved but it took a turn for the worse - all icons got the old-version-look. 

Can you help me with the same by providing me with the "qBitTorrent theme 2.9" look and font "Segoe UI"?

Thanks in advance!

Font issue with letters "o" and "a" in font "Segoe UI Variable Text" in Default Dark Theme.
![Screenshot with o and a issue](https://user-images.githubusercontent.com/85340126/214919587-5b4d6f73-ae35-436d-bee4-60b64a82fc5c.png)
Icons issue with re-built theme.
![Screenshot old icons](https://user-images.githubusercontent.com/85340126/214921054-a21c0c0c-20a3-480f-97fd-f96c9d3e2fcb.png)
Default Icons in Dark Theme.
![Screenshot new icons](https://user-images.githubusercontent.com/85340126/214921193-22faf054-21d0-421a-9e7e-5762df0e1890.png)

**Comment by witalihirsch** [comment]
you just need to delete or rename the folder with icons so that the script doesn't read the path to the icons and run the script again, then the icons will be by default
