### ISSUE TITLE
Request: Compact version

### ISSUE THREAD

**Issue by fossist** [witalihirsch/qBitTorrent-fluent-theme#37]
This theme is really good and perfectly matches with the windows 11 style. However, it uses more space than the original theme. If you have time, will you please do a compact version of this theme like the original one?

**Comment by witalihirsch** [comment]
I'm sorry, but I don't have that much time to do this. You can customize the theme yourself by editing the `.qss` file in `Builds` > `fluent-theme`. You can reduce the size of objects by changing the values of `padding`, `height`, `width` to your liking. After the changes, go to `Builds` and run the `.bat` file depending on the theme you changed and a new file with the `.qbtheme` extension will appear in the same directory.

**Comment by fossist** [comment]
Thanks for the instructions.
