### ISSUE TITLE
Popup text cropped

### ISSUE THREAD

**Issue by dr-baba** [witalihirsch/qBitTorrent-fluent-theme#4]
Hi a bug I found after installing the new version.
![image](https://user-images.githubusercontent.com/50979846/173087713-ee058e48-4f37-4fc3-bc89-3671a7a850e6.png)

**Comment by dr-baba** [comment]
Also, the blue tick indicators on the download window are gone.
![image](https://user-images.githubusercontent.com/50979846/173168534-1da17d57-065c-4aa3-be72-fbbdc3a7d734.png)

**Comment by maisans-maid** [comment]
the same with no-mica version. Hoping for a fix

**Comment by witalihirsch** [comment]
> Hi a bug I found after installing the new version. ![image](https://user-images.githubusercontent.com/50979846/173087713-ee058e48-4f37-4fc3-bc89-3671a7a850e6.png)

fixed, see new release

**Comment by witalihirsch** [comment]
> Also, the blue tick indicators on the download window are gone. ![image](https://user-images.githubusercontent.com/50979846/173168534-1da17d57-065c-4aa3-be72-fbbdc3a7d734.png)

fixed, see new release
