### ISSUE TITLE
Does not work in qBittorrent 4.6.0

### ISSUE THREAD

**Issue by oomek** [witalihirsch/qBitTorrent-fluent-theme#52]
The UI is still white, just the icons have changed.
![image](https://github.com/witalihirsch/qBitTorrent-fluent-theme/assets/2974860/1551d532-7979-4b19-9d80-41e66b2c24bd)

**Comment by tejasraman** [comment]
4.6.0 is still in beta..... the theme works fine in 4.5.4, that beta is (presumably) NOT supported

**Comment by oomek** [comment]
Ok, I've installed 4.5.4. Looks very nice. Thanks.
